---
- hosts: all
  become: false
  vars:
    temp_address: 192.168.1.231
    dc_address: 192.168.1.100
    dc_netmask_cidr: 24
    dc_gateway: 192.168.1.254
    dc_hostname: 'win-01'
    domain_name: "dev.local"
    local_admin: '.\administrator'
    temp_password: 'P4ssw0rd'
    dc_password: 'P4ssw0rd'
    recovery_password: 'P4ssw0rd'
    upstream_dns_1: 192.168.1.254
    reverse_dns_zone: "192.168.1.0/24"
    ntp_servers: "0.us.pool.ntp.org,1.us.pool.ntp.org"
  tasks:
  - name: Install Active Directory
    win_feature: >
         name=AD-Domain-Services
         include_management_tools=yes
         include_sub_features=yes
         state=present
    register: result
    delegate_to: '{{ dc_address }}'
  - name: Create Domain
    win_domain: >
       dns_domain_name='{{ domain_name }}'
       safe_mode_password='{{ recovery_password }}' 
    register: ad
    delegate_to: "{{ dc_address }}"
  - name: reboot server
    win_reboot:  
       msg: "Installing AD. Rebooting..."
       pre_reboot_delay: 15
    when: ad.changed
    delegate_to: "{{ dc_address }}"
