---
- hosts: all
  tasks:
  - name: Get Operating System
    debug:
      msg: "{{ ansible_distribution }} {{ ansible_fqdn }}"
      
  - name: yum_command 
    yum:
      name: '*'
      state: latest
