---
- hosts: all
  tasks:
  - name: Checking linux Connectivity
  #  gather_facts: false
  ignore_errors: true
  ignore_unreachable: true
  become: true
  tasks:
    - name: Checking Linux Connectivity
      shell: whoami
      register: cmdopt
    - debug: var=cmdopt
    - debug: msg="Unble to reach endpoint"
      when:  cmdopt.failed|default("true")
    - debug: msg="Able to reach endpoint"
      when: cmdopt.changed |default("false")
  - name: Get Operating System
    debug:
      msg: "{{ ansible_distribution }} {{ ansible_default_ipv4 }}"
      
  - name: Run yum update 
    yum:
      name: '*'
      state: latest

  - name: Ensure group "admins" exists
    group:
      name: admins
      state: present

  - name: Add the user 'Zippy' with a specific uid and a primary group of 'admin'
    user:
      name: zippy
      comment: Zippy
      uid: 1040
      group: admins

  - name: iptables flush filter
    iptables:
      chain: "{{ item }}"
      flush: yes
    with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]

  - name: Change Motd
    template:
      src: templates/motd.j2
      dest: /etc/motd
      mode: 0444
      
