---
- hosts: all
  gather_facts: True
  ignore_errors: true
  ignore_unreachable: true
  become: true
  tasks:
  - name: Checking Linux Connectivity
    shell: whoami
    register: cmdopt
  - debug: var=cmdopt
  - debug: msg="Unble to reach endpoint"
    when:  cmdopt.failed|default("true")
  - debug: msg="Able to reach endpoint"
    when: cmdopt.changed |default("false")
  - name: Get Operating System
    debug:
      msg: "{{ ansible_distribution }} {{ ansible_default_ipv4 }}"
      
  - name: Run yum update 
    yum:
      name: '*'
      state: latest

  - name: iptables flush filter
    iptables:
      chain: "{{ item }}"
      flush: yes
    with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]

  - name: Change Motd
    template:
      src: templates/motd.j2
      dest: /etc/motd
      mode: 0444
 
 include_vars: vars/main.yaml
 
  - name: Install packages
    yum:
      name: "{{ packages }}"
      state: latest
      
