---
- hosts: all
  become: false
  tasks:
  - name: Get Windows version
    debug:
      msg: "{{ ansible_distribution }}"
      
  - name: Check for Windows updates
    win_updates:
      categories: CriticalUpdates
    reboot: yes
